DATALOADER:
  TRAIN_X:
    # 4 imgs is 24GB/1GPU
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 1024
  NUM_WORKERS: 8

INPUT:
  SIZE: (48, 48, 48)
#  SIZE: (48, 48, 1)  # Braincell
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073] # mean [0.4491643]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711] # mean
#  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]
#  TRANSFORMS: ["random_resized_crop", "random_flip", "rotate", 'medmnist_3Dtransform', 'intensity_percent']
  TRANSFORMS: ["random_flip", "rotate", "braincell_centercrop"]
#  TRANSFORMS: ["random_flip", "braincell_centercrop"]
#  TRANSFORMS: ['medmnist_3Dtransform']
#  TRANSFORMS: ["braincell_centercrop"]
#  TRANSFORMS: []

OPTIM:
  NAME: "sgd"
#  LR: 2e-3
  MAX_EPOCH: 200
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  # Either linear or constant
  WARMUP_TYPE: "constant"
  # Constant learning rate when type=constant
  WARMUP_CONS_LR: 1e-5
  # Minimum learning rate when type=linear
  WARMUP_MIN_LR: 1e-5
  # Recount epoch for the next scheduler (last_epoch=-1)
  # Otherwise last_epoch=warmup_epoch
  WARMUP_RECOUNT: True

TRAIN:
  PRINT_FREQ: 5

TEST:
  COMPUTE_CMAT: True

MODEL:
  BACKBONE:
    NAME: "ViT3D-B/16"

DATASET:
  VAL_SET: ""
  TEST_SET: "val"
  TRAIN_SET: "train"
#  VAL_SET: "val"
#  TEST_SET: "test"
#  TRAIN_SET: "train"
  CENTER_CROP: False
